### ISSUE TITLE
Make it work for the original circuit?

### ISSUE THREAD

**Issue by inktrap** [martin-stone/ctpatch#1]
How much effort would be needed to make this work for the original novation circuit?

**Comment by martin-stone** [comment]
According to this...

https://www.reddit.com/r/novationcircuit/comments/mc1mvw/using_tracks_patches_in_original_circuit/

... it should work for both, and just the [Header.prod_num](https://github.com/martin-stone/ctpatch/blob/main/ctpatch.py#L287) value will be different.

Currently some [validation code](https://github.com/martin-stone/ctpatch/blob/main/ctpatch.py#L501) will complain, but that's easily fixed.

**Comment by martin-stone** [comment]
I've pushed some changes to [this branch](https://github.com/martin-stone/ctpatch/tree/og-support) that should make it work. Do you have an original circuit that you could test with?

For a quick test, you can do something like...

```python
import ctpatch
from pprint import pprint

p = ctpatch.read_syx("example.syx")
pprint(p)
```

**Comment by martin-stone** [comment]
Actually I only need to test it on a original circuit .syx file, so I did that and merged the changes. It should now work for both.

**Comment by inktrap** [comment]
Awesome! I in fact have an OG Circuit and could test this; i'll get back to you :)
